#!/bin/bash 

#pocet cisel bud zadam nebo 10 :)
if [ $# -lt 1 ];then 
    numbers=10;
else
    numbers=$1;
fi;

#preklad cpp zdrojaku
mpiCC --prefix /usr/local/share/OpenMPI -o mes mes.c -lm

#vyrobeni souboru s random cisly
dd if=/dev/urandom bs=1 count=$numbers of=numbers > /dev/null 2>&1

#spusteni
mpirun --prefix /usr/local/share/OpenMPI -np $((2*$numbers -1)) mes

#uklid
rm -f mes  numbers

